"""Added comment model

Revision ID: 268b5352f62f
Revises: 9e471a1d21b2
Create Date: 2022-03-13 15:21:55.906658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268b5352f62f'
down_revision = '9e471a1d21b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_blog_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_blog_fkey', 'comment', 'blog', ['blog'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'blog_id')
    # ### end Alembic commands ###
