"""add phone number

Revision ID: 725fcf58bb2e
Revises: 95e3e43e22c1
Create Date: 2022-03-16 21:12:48.986200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725fcf58bb2e'
down_revision = '95e3e43e22c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
