"""add tranee table

Revision ID: 95e3e43e22c1
Revises: a3091283f4db
Create Date: 2022-03-16 15:22:21.453358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e3e43e22c1'
down_revision = 'a3091283f4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
